### ISSUE TITLE
Quality of Life Improvements

### ISSUE THREAD

**Issue by KarlosWGeek** [The-Fireplace-Minecraft-Mods/Clans#224] opened 2020-06-03 00:15 UTC
- Option to **disable claiming in specific dimension** (can't claim land in the Nether or in the End, for example);
 - Option to **protect recently created clans from raids** for a configurable amount of time;
 - Option to make **raids only happen when more than _x_ players are online (defending clan);**
 - Option to **set a maximum number of players in a clan;**
 - **JourneyMap integration/support:** clans are visible on minimap, fullscreen map or both;

**Comment by The-Fireplace** [comment] 2020-06-03 07:52
Thanks for the suggestions!
1. This is a feature in Clans 2.0.0, which is available [here](https://www.patreon.com/posts/37806225) and will be posted on CurseForge on June 16.
2. This is already a config option, `initialShieldTime`.
3. Very similar to #218 , I've added a note to that to make it percentage based and/or a set number.
4. Duplicate of #215 
5. Duplicate of #80 

For future reference, please make a separate issue with each feature you are requesting.

**Closed as completed by The-Fireplace** 2020-06-03 07:52 UTC
Labels: enhancement

**Comment by mcqwy** [comment] 2020-07-31 17:36
Is this feature implemented in version 2.0.1?

**Comment by The-Fireplace** [comment] 2020-07-31 20:37
@mcqwy Yes
