### ISSUE TITLE
Disable Nucleus /fly command during raid

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#179] opened 2020-03-09 23:10 UTC
Add a list of disable directives to the configuration file of clan.

**Comment by The-Fireplace** [comment] 2020-03-09 23:14
Because /fly is not a vanilla command, I'll need to know which plugin you are using that adds it.

**Comment by mcqwy** [comment] 2020-03-09 23:16
Sponge.
Nucleus-1.14.1-S7.1-MC1.12.2-plugin.

**Comment by mcqwy** [comment] 2020-03-09 23:16
Can you do this, please?

**Comment by The-Fireplace** [comment] 2020-03-09 23:17
I will look in to it.

**Comment by mcqwy** [comment] 2020-03-09 23:17
Thank you

**Comment by The-Fireplace** [comment] 2020-03-13 01:24
Duplicate of #70

**Closed as completed by The-Fireplace** 2020-03-13 01:24 UTC
Labels: duplicate, enhancement, mod compat
